import { CssBaseline } from "@mui/material";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <CssBaseline />
      <body>{children}</body>
    </html>
  );
}
